{
    'name': 'Students',
    'version': '19.0.1.0.1',
    'category': 'sales',
    'author': 'Himanshu',
    'depends': ['base','mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/security_groups.xml',
        'security/record_rules.xml',
        'views/wizard_view.xml',
        'views/views.xml',
        'views/templates.xml',
        'data/student.info.csv',
        'data/student_category.xml',
        'data/birthday_email.xml',
        # 'data/cron.xml',
        # 'data/cron_2.xml',
        'demo/demo_data.xml',
    ],
    'installable': True,
    'application': True,
}
