{
    'name':'Odoo',
    'version':'19.0.1.0.1',
    'category':'sales',
    'author':'Himanshu',
    'depends':['base'],
    'data':[
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    'installable':True,
    'application':True,
}